# .github/workflows/Angular_DockerImage.yml
name: Angular_DockerImage Build and Push

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_push_docker_image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20.x # O la versión que necesites

    - name: Install dependencies
      run: npm ci

    - name: Build Angular application # Genera dist/mycv/browser
      run: npm run build

    # --- Pasos para construir y subir la imagen Docker ---

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      # Este paso ejecuta 'docker build' usando el Dockerfile.
      # La instrucción COPY dentro del Dockerfile se ejecuta aquí.
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile # Especifica tu Dockerfile
        push: true
        tags: |
          ${{ secrets.DOCKER_USER }}/mycv:${{ github.sha }}
          ${{ secrets.DOCKER_USER }}/mycv:latest

    # --- Ya no necesitas los pasos manuales de docker run, cp, commit, push ---
